---
name: Cache-Repository
version: 0.06
author:
  - 'Darin McBride - dmcbride@cpan.org'
abstract: Generic repository of files
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Filesys::DiskUsage: 0.04
  perl: 5.8.0
recommends:
  Filesys::Statvfs: 0
provides:
  Cache::Repository:
    file: lib/Cache/Repository.pm
    version: 0.06
  Cache::Repository::Filesys:
    file: lib/Cache/Repository/Filesys.pm
    version: 0.04
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
